### ISSUE TITLE
Remove `api-approved.kubernetes.io` annotation from CRDs

### ISSUE THREAD

**Issue by cici37** [kubernetes/cel-admission-webhook#9]
Update: remove `api-approved.kubernetes.io` annotation from CRDs
/cc @alexzielenski @jiahuif

**Comment by alexzielenski** [comment]
I dont think it violates the guidelines since we use `.x-k8s.io` suffix (opposed to `.k8s.io`. If our CRDs currently have the `api-approved` annotation it is vestigial and should be able to be removed without issue.

**Comment by cici37** [comment]
> I dont think it violates the guidelines since we use `.x-k8s.io` suffix (opposed to `.k8s.io`. If our CRDs currently have the `api-approved` annotation it is vestigial and should be able to be removed without issue.

Yes `x-k8s.io` should be ok and we should remove the annotation in this case. Thank you!

/retitle Remove `api-approved.kubernetes.io` annotation from CRDs
